included:
  - MacMCP/Sources
  - MacMCP/Tests
excluded:
  - MacMCP/.build
  - MacMCP/swift-sdk
  - "**/.*.swift"

disabled_rules:
  - trailing_whitespace  # Let swift-format handle this
  - line_length          # Let swift-format handle this
  - function_body_length
  - type_body_length
  - file_length
  - todo
  - vertical_whitespace  # Let swift-format handle spacing
  - opening_brace        # Let swift-format handle brace placement

opt_in_rules:
  - force_unwrapping
  - implicit_return
  - closure_spacing
  - unneeded_parentheses_in_closure_argument
  - redundant_nil_coalescing
  - overridden_super_call
  - prohibited_super_call
  - empty_count
  - empty_string
  - first_where
  - modifier_order
  - sorted_imports

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 3

identifier_name:
  excluded:
    - id
    - x
    - y
    - w
    - h
    - i
    - j
    - ax

# Ensure SwiftFormat and SwiftLint agree on trailing commas
trailing_comma:
  mandatory_comma: true

reporter: "xcode"